### PR TITLE
Modernised build and publish scripts

### LINKED ISSUE #2721: Source map error
After updating to version 7.1.0 (From 6.5.0) we get the following error:

WARNING in ../../node_modules/@turf/jsts/dist/jsts.min.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/node_modules/@turf/jsts/dist/jsts.min.js.map' file: Error: ENOENT: no such file or directory, open '//node_modules/@turf/jsts/dist/jsts.min.js.map'

Could the sourcemaps be included?

### PR DESCRIPTION
**Pull request by smallsaucepan**
Updated build and publish scripts in preparation for a minor release. Short term goal is to fix https://github.com/Turfjs/turf/issues/2721 by including the generated map in the dist/ directory.

### CODE REVIEW

**Comment by smallsaucepan** [comment]
Care to cast an eye over this @JamesLMilner? Any concerns or suggestions?

File: test/test.js [hunk 1]
```diff
@@ -1,15 +1,37 @@
...
-
-console.log("GeoJSONReader");
-console.assert(jsts.GeoJSONReader !== undefined, true);
-console.log("GeoJSONReader is present");
-
-console.log("GeoJSONWriter");
-console.assert(jsts.GeoJSONWriter !== undefined, true);
-console.log("GeoJSONWriter is present");
+
+if (jsts !== undefined && typeof jsts === "object") {
```
Comment (JamesLMilner) [inline test/test.js]: Without the console.asserts nothing will fail here I don't think? I.e. the exit code will be 0 rather than 1

**Review by JamesLMilner — COMMENTED** [review]
Looks good, one comment about the test changes

File: test/test.js (hunk 1 above)
Comment (smallsaucepan) [reply test/test.js]: I'm pretty sure console.asserts just prints conditionally. Making this an "informational" test run, rather than something that passes or fails. Can change to be more like that if you want?

Comment (JamesLMilner) [reply test/test.js]: Oh yes, you are right. I feel like if the exit code for this script is not 1 then it won't block CI? Maybe there should be a Boolean called failed and it should be set to true in the if blocks? Then at the end it can throw an error if failed is set to true?

Comment (smallsaucepan) [reply test/test.js]: How about I convert them to tape tests?

**Comment by smallsaucepan** [comment]
Test script converted to tape tests 👍

File: test/test.js (hunk 1 above)
Comment (JamesLMilner) [reply test/test.js]: I think that would be good if you have the time/willpower. I think my thought process was that we would in theory eventually delete this module as we managed to get buffer working without it, so I didn't do anything too involved. However I think it's here for the foreseeable so potentially worthwhile!

Comment (smallsaucepan) [reply test/test.js]: Already done! Merge whenever you like.

> we managed to get buffer working without it

Is that a PR somewhere? turf-buffer is definitely still using BufferOp.

**Review by JamesLMilner — APPROVED** [review]
